---
# file     : roles/labipa-users/defaults/main.yml
# purpose  : variable file for labipa-users role
#
# author   : harald van der laan
# date     : 2017/03/15
# version  : v1.0.0
#
# changelog:
# - v1.0.0    initial version

labipa_users:
  - { user: "lisa", first: "lisa", last: "doe" }
  - { user: "linda", first: "linda", last: "doe" }
  - { user: "thomsen", first: "thomsen", last: "doe" }
  - { user: "ldapuser1", first: "ldap", last: "user1" }
  - { user: "ldapuser2", first: "ldap", last: "user2" }
  - { user: "ldapuser3", first: "ldap", last: "user3" }
  - { user: "ldapuser4", first: "ldap", last: "user4" }
  - { user: "ldapuser5", first: "ldap", last: "user5" }
  - { user: "isabelle", first: "isa", last: "belle" }
